name: schedule_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+1
  path_provider: ^2.0.11
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  flutter_bloc: ^8.1.5
  postgres: ^2.6.4
  intl: ^0.19.0
  screenshot: ^3.0.0
  share: ^2.0.4
  flutter_image_saver : ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

